processes:
- name: standalone-7
  executable: /var/vcap/packages/redis-7/bin/redis-server
  args:
  - /var/vcap/jobs/standalone-7/config/redis.conf
  env:
    LANG: en_US.UTF-8
  limits:
<% if p('vm.memory_mb') && (p('vm.memory_mb').to_i > 0) -%>
    memory: <%= p('vm.memory_mb').to_i %>
<% end -%>
    open_files: 65536
  ephemeral_disk: true
  persistent_disk: true
  unsafe:
    privileged: true
    host_pid_namespace: true
  capabilities:
  - NET_BIND_SERVICE
<% if p('persistent') %>
  workdir: /var/vcap/store/standalone-7
<% end %>