---
meta:
  size: default
  password: (( vault $CREDENTIALS "/redis/system:password" ))
  masters:   2
  replicas:  2
  instances: 4
  default:
    azs: [z1, z2]

releases:
  - { name: redis-forge, version: latest }

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
  - name: node
    instances: (( grab meta.instances ))
    azs: (( grab meta.azs || meta.default.azs ))
    networks: [name: (( grab meta.net || "redis-service" ))]
    stemcell: default
    vm_type: (( grab meta.size ))

    jobs:
      - name:    cluster
        release: redis-forge
        properties:
          auth:
            password: (( grab meta.password ))

          cluster:
            masters:  (( grab meta.masters ))
            replicas: (( grab meta.replicas ))
          redis:
            maxmemory-policy: (( grab meta.params.maxmemory-policy || meta.redis_maxmemory-policy || "allkeys-lru" ))
            notify-keyspace-events: (( grab meta.params.notify-keyspace-events || meta.redis_notify-keyspace-events || "" ))
            slowlog-log-slower-than: (( grab meta.params.slowlog-log-slower-than || meta.redis_slowlog-log-slower-than || 10000 ))
            slowlog-max-len: (( grab meta.params.slowlog-max-len || meta.redis_slowlog-max-len || 128 ))
            maxmemory: (( grab meta.redis_maxmemory || 0 ))
          lua:
            scripting-enabled: (( grab meta.lua_scripting_enabled || true ))
          client:
            timeout: (( grab meta.client_timeout || 0 ))
            tcpkeepalive: (( grab meta.client_tcpkeepalive || 300 ))
            connections: (( grab meta.client_connections || 10000 ))
