---
meta:
  size: default
  disk_config: {}
  default:
    azs: [ z1 ]
  password: (( vault $CREDENTIALS "/redis/system:password" ))

releases:
  - { name: redis-forge, version: latest }

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

features:
  randomize_az_placement: true

instance_groups:
  - name: standalone
    instances: 1
    networks: [name: (( grab meta.net || "redis-service" ))]
    stemcell: default
    azs: (( grab meta.azs || meta.default.azs ))
    vm_type: (( grab meta.size ))

    # This is a workaround to make sure only one of `persistent_disk`
    # and `persistent_disk_type` is defined.
    .: (( inject meta.disk_config ))

    jobs:
      - name:    standalone
        release: redis-forge
        properties:
          auth:
            password: (( grab meta.password ))
          persistent: (( grab meta.persistent ))
          redis:
            maxmemory-policy: (( grab meta.params.maxmemory-policy || meta.redis_maxmemory-policy || "allkeys-lru" ))
            notify-keyspace-events: (( grab meta.params.notify-keyspace-events || meta.redis_notify-keyspace-events || "" ))
            slowlog-log-slower-than: (( grab meta.params.slowlog-log-slower-than || meta.redis_slowlog-log-slower-than || 10000 ))
            slowlog-max-len: (( grab meta.params.slowlog-max-len || meta.redis_slowlog-max-len || 128 ))
            maxmemory: (( grab meta.redis_maxmemory || 0 ))
            no-appendfsync-on-rewrite: (( grab meta.redis_no-appendfsync-on-rewrite || false ))
            auto-aof-rewrite-percentage: (( grab meta.redis_auto-aof-rewrite-percentage || 100 ))
            auto-aof-rewrite-min-size: (( grab meta.redis_auto-aof-rewrite-min-size || "64mb" ))
          lua:
            scripting-enabled: (( grab meta.lua_scripting_enabled || true ))
          client:
            timeout: (( grab meta.client_timeout || 0 ))
            tcpkeepalive: (( grab meta.client_tcpkeepalive || 300 ))
            connections: (( grab meta.client_connections || 10000 ))
